---
- name: Windows Test Playbook
  hosts: win, win_old, win_local
  tasks:
    - name: Remote Execute the mqsc files
      win_shell: |
        hostname
        Get-Date
      register: scriptoutput
    - name: Script output
      debug: var=scriptoutput.stdout
